### ISSUE TITLE
Sporadically some line overflows

### ISSUE THREAD

**Issue by CamilleScholtz** [egilll/tex-linebreak2#4] opened 2022-08-22 16:36 UTC
Sometimes when I refresh (both soft and hard page refreshes), one or two lines in the document bug out and overflows:

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/5213535/185972896-4430800c-57be-4eb8-b981-2babb818488d.png">

I thought the cause was that maybe not all the fonts were properly loaded, so I added some timeout, however it seems this might actually worsen the bug? Code:

```js
     document.fonts.ready.then(() => {
         texLinebreak.texLinebreakDOM(main.querySelectorAll(".content>p, .content>blockquote p, .content>li p, .welcomments__comment-message"));

         setTimeout(() => {
             texLinebreak.texLinebreakDOM(main.querySelectorAll(".content>p, .content>blockquote p, .content>li p, .welcomments__comment-message"));
         }, 1000);
     });
```

Page where this happens: https://reactionair.nl/artikelen/het-verval-van-de-archetypen/

- - -

I think I found how to reproduce this problem, it seems to happen when I refresh the page when my viewport is halfway through the article.

**Comment by egilll** [comment] 2022-08-23 10:46
This was caused by the code taking into account the position of hidden floating elements and the floating elements in the sticky header.

I've pushed a fix for this issue. I've also added an option, `ignoreFloatingElements`, to ignore all floating elements in case people run into other edge cases.

**Closed as completed by egilll** 2022-08-23 10:46 UTC
